In [1]:
import pandas as pd

# Import first MyCNN ternary classification results
myCNN1_df = pd.read_csv("experiments.csv")

In [2]:
# Inspect columns
myCNN1_df[["acc_normal","acc_benign","acc_malignant"]]

    acc_normal  acc_benign  acc_malignant
0     0.961297    0.000000       0.019656
1     0.416019    0.454545       0.668305
2     0.615063    0.370497       0.692875
3     0.523162    0.619211       0.542998
4     0.822475    0.217839       0.511057
5     0.193814    0.454545       0.668305
6     0.741184    0.348199       0.702703
7     0.414824    0.456261       0.636364
8     0.346683    0.166381       0.923833
9     0.683951    0.188679       0.656020
10    0.739540    0.144082       0.638821
11    0.699342    0.603774       0.262899
12    0.684698    0.351630       0.579853
13    0.706964    0.353345       0.609337
14    0.391811    0.262436       0.825553
15    0.487448    0.123499       0.943489
16    0.246862    0.586621       0.579853
17    0.674985    0.348199       0.712531
18    0.394501    0.634648       0.515971
19    0.910042    0.104631       0.633907
20    0.635535    0.054889       0.911548
21    0.697101    0.283019       0.557740
22    0.587268    0.149228       0.751843
23    0.645397    0.559177       0.321867
24    0.739839    0.548885       0.282555

In [3]:
# Get averages of three experiments
cols_to_average = ["acc_normal","acc_benign","acc_malignant"]

myCNN1_avg_df = (
    myCNN1_df.iloc[:-1][cols_to_average]
      .groupby(myCNN1_df.iloc[:-1].index // 3)
      .mean()
      .reset_index(drop=True)
)

In [4]:
# Display averages
myCNN1_avg_df

   acc_normal  acc_benign  acc_malignant
0    0.664126    0.275014       0.460278
1    0.513150    0.430532       0.574120
2    0.500897    0.323613       0.754300
3    0.707611    0.312178       0.519247
4    0.594491    0.322470       0.671581
5    0.469765    0.352773       0.745291
6    0.646693    0.264723       0.687142
7    0.643256    0.330475       0.543817

In [5]:
# Import second MyCNN ternary classification results
myCNN2_df = pd.read_csv("experiments_v2.csv")

In [6]:
# Total time in hours and average time in minutes taken
print((myCNN2_df["training_time_min"].sum())/60)
print(myCNN2_df["training_time_min"].mean())

16.903517965873085
7.862101379475853

In [7]:
# Get averages of three experiments
cols_to_average2 = ["training_time_min","acc_normal","acc_benign","acc_malignant"]

myCNN2_avg_df = (
    myCNN2_df[cols_to_average2]      # select columns
      .groupby(myCNN2_df.index // 3)
      .mean()
      .reset_index(drop=True)
)

In [8]:
# Display averages
myCNN2_avg_df

    training_time_min  acc_normal  acc_benign  acc_malignant
0            7.650024    0.516637    0.245855       0.813268
1            6.310023    0.648884    0.152087       0.865684
2            5.768608    0.716726    0.559748       0.415233
3            1.748712    0.660889    0.379074       0.490581
4            1.906106    0.643206    0.453402       0.446355
5            2.710900    0.644999    0.496855       0.414414
6            3.200758    0.767085    0.499142       0.203112
7            6.862877    0.894750    0.387650       0.196560
8            7.586700    0.956515    0.336764       0.276003
9            8.885532    0.976340    0.280160       0.115479
10           5.794931    0.986252    0.098342       0.108108
11           6.779506    0.988942    0.090337       0.352989
12           6.700615    0.948496    0.237850       0.205569
13           9.767279    0.953776    0.255003       0.440622
14           9.012011    0.952630    0.423671       0.045045
15           5.444386    0.981670    0.269868       0.091728
16          15.429163    0.944909    0.252716       0.191646
17          15.458395    0.963339    0.261292       0.316134
18          12.915872    0.968719    0.176672       0.096642
19          19.987768    0.947871    0.553682       0.146322
20          11.438559    0.946971    0.402473       0.085290
21          11.469817    0.957527    0.188308       0.248044
22          47.513315    0.864676    0.523328       0.355243
23          40.272255    0.893291    0.453626       0.194053
24           0.779661    0.721797    0.160202       0.651017
25           0.530623    0.718545    0.197864       0.632238
26           0.569032    0.645405    0.087690       0.754304
27           0.598183    0.653409    0.098932       0.760563
28           0.683837    0.892791    0.180438       0.245696
29           1.145916    0.963930    0.114671       0.075900
30           2.209944    0.813147    0.377740       0.362285
31           2.208831    0.797188    0.311973       0.439750
32           3.210932    0.752364    0.286678       0.532081
33           2.878374    0.689179    0.468241       0.449922
34           3.249103    0.763720    0.426644       0.535211
35           4.685927    0.824003    0.503654       0.354460
36           5.258882    0.806944    0.364812       0.533646
37           5.907917    0.879284    0.438449       0.314554
38           7.392850    0.911151    0.594716       0.201878
39           6.503407    0.902046    0.385610       0.385759
40           7.009068    0.900545    0.608769       0.223787
41           5.648646    0.988844    0.201799       0.032864
42           6.985113    0.818000    0.449129       0.437402

In [10]:
# Create a column with the sum of accuracies
myCNN2_avg_df["acc_total"] = myCNN2_avg_df["acc_normal"] + myCNN2_avg_df["acc_benign"] + myCNN2_avg_df["acc_malignant"]

In [11]:
# Display results
myCNN2_avg_df

    training_time_min  acc_normal  acc_benign  acc_malignant  acc_total
0            7.650024    0.516637    0.245855       0.813268   1.575759
1            6.310023    0.648884    0.152087       0.865684   1.666655
2            5.768608    0.716726    0.559748       0.415233   1.691708
3            1.748712    0.660889    0.379074       0.490581   1.530544
4            1.906106    0.643206    0.453402       0.446355   1.542963
5            2.710900    0.644999    0.496855       0.414414   1.556269
6            3.200758    0.767085    0.499142       0.203112   1.469340
7            6.862877    0.894750    0.387650       0.196560   1.478960
8            7.586700    0.956515    0.336764       0.276003   1.569282
9            8.885532    0.976340    0.280160       0.115479   1.371979
10           5.794931    0.986252    0.098342       0.108108   1.192702
11           6.779506    0.988942    0.090337       0.352989   1.432269
12           6.700615    0.948496    0.237850       0.205569   1.391915
13           9.767279    0.953776    0.255003       0.440622   1.649401
14           9.012011    0.952630    0.423671       0.045045   1.421346
15           5.444386    0.981670    0.269868       0.091728   1.343266
16          15.429163    0.944909    0.252716       0.191646   1.389271
17          15.458395    0.963339    0.261292       0.316134   1.540766
18          12.915872    0.968719    0.176672       0.096642   1.242033
19          19.987768    0.947871    0.553682       0.146322   1.647876
20          11.438559    0.946971    0.402473       0.085290   1.434734
21          11.469817    0.957527    0.188308       0.248044   1.393878
22          47.513315    0.864676    0.523328       0.355243   1.743246
23          40.272255    0.893291    0.453626       0.194053   1.540970
24           0.779661    0.721797    0.160202       0.651017   1.533017
25           0.530623    0.718545    0.197864       0.632238   1.548647
26           0.569032    0.645405    0.087690       0.754304   1.487398
27           0.598183    0.653409    0.098932       0.760563   1.512905
28           0.683837    0.892791    0.180438       0.245696   1.318926
29           1.145916    0.963930    0.114671       0.075900   1.154501
30           2.209944    0.813147    0.377740       0.362285   1.553172
31           2.208831    0.797188    0.311973       0.439750   1.548911
32           3.210932    0.752364    0.286678       0.532081   1.571123
33           2.878374    0.689179    0.468241       0.449922   1.607341
34           3.249103    0.763720    0.426644       0.535211   1.725575
35           4.685927    0.824003    0.503654       0.354460   1.682117
36           5.258882    0.806944    0.364812       0.533646   1.705402
37           5.907917    0.879284    0.438449       0.314554   1.632286
38           7.392850    0.911151    0.594716       0.201878   1.707745
39           6.503407    0.902046    0.385610       0.385759   1.673415
40           7.009068    0.900545    0.608769       0.223787   1.733101
41           5.648646    0.988844    0.201799       0.032864   1.223506
42           6.985113    0.818000    0.449129       0.437402   1.704531

In [14]:
# Weighted residuals calculated as (1 - accuracy) multiplied by an importance factor (normal: 1, benign: 2, malignant: 4)
cols = ["acc_normal", "acc_benign", "acc_malignant"]

weights = pd.Series({
    "acc_normal": 1,
    "acc_benign": 2,
    "acc_malignant": 4
})

residuals = 1 - myCNN2_avg_df[cols]

# myCNN2_avg_df["residual_sum"] = residuals.sum(axis=1)
myCNN2_avg_df["weighted_residual"] = (residuals * weights).sum(axis=1)

In [15]:
# Display
myCNN2_avg_df

,training_time_min,acc_normal,acc_benign,acc_malignant,acc_total,weighted_residual
0,7.650024,0.516637,0.245855,0.813268,1.575759,2.738582
1,6.310023,0.648884,0.152087,0.865684,1.666655,2.584206
2,5.768608,0.716726,0.559748,0.415233,1.691708,3.502843
3,1.748712,0.660889,0.379074,0.490581,1.530544,3.618638
4,1.906106,0.643206,0.453402,0.446355,1.542963,3.664569
5,2.710900,0.644999,0.496855,0.414414,1.556269,3.703633
6,3.200758,0.767085,0.499142,0.203112,1.469340,4.422181
7,6.862877,0.894750,0.387650,0.196560,1.478960,4.543709
8,7.586700,0.956515,0.336764,0.276003,1.569282,4.265944
9,8.885532,0.976340,0.280160,0.115479,1.371979,5.001423
10,5.794931,0.986252,0.098342,0.108108,1.192702,5.384632
11,6.779506,0.988942,0.090337,0.352989,1.432269,4.418426
12,6.700615,0.948496,0.237850,0.205569,1.391915,4.753527
13,9.767279,0.953776,0.255003,0.440622,1.649401,3.773729
14,9.012011,0.952630,0.423671,0.045045,1.421346,5.019848
15,5.444386,0.981670,0.269868,0.091728,1.343266,5.111681
16,15.429163,0.944909,0.252716,0.191646,1.389271,4.783074
17,15.458395,0.963339,0.261292,0.316134,1.540766,4.249539
18,12.915872,0.968719,0.176672,0.096642,1.242033,5.291368
19,19.987768,0.947871,0.553682,0.146322,1.647876,4.359475
20,11.438559,0.946971,0.402473,0.085290,1.434734,4.906925
21,11.469817,0.957527,0.188308,0.248044,1.393878,4.673682
22,47.513315,0.864676,0.523328,0.355243,1.743246,3.667699
23,40.272255,0.893291,0.453626,0.194053,1.540970,4.423245
24,0.779661,0.721797,0.160202,0.651017,1.533017,3.353729
25,0.530623,0.718545,0.197864,0.632238,1.548647,3.356775
26,0.569032,0.645405,0.087690,0.754304,1.487398,3.162001
27,0.598183,0.653409,0.098932,0.760563,1.512905,3.106473
28,0.683837,0.892791,0.180438,0.245696,1.318926,4.763546
29,1.145916,0.963930,0.114671,0.075900,1.154501,5.503128
30,2.209944,0.813147,0.377740,0.362285,1.553172,3.982233
31,2.208831,0.797188,0.311973,0.439750,1.548911,3.819867
32,3.210932,0.752364,0.286678,0.532081,1.571123,3.545955
33,2.878374,0.689179,0.468241,0.449922,1.607341,3.574653
34,3.249103,0.763720,0.426644,0.535211,1.725575,3.242147
35,4.685927,0.824003,0.503654,0.354460,1.682117,3.750849
36,5.258882,0.806944,0.364812,0.533646,1.705402,3.328848
37,5.907917,0.879284,0.438449,0.314554,1.632286,3.985603
38,7.392850,0.911151,0.594716,0.201878,1.707745,4.091905
39,6.503407,0.902046,0.385610,0.385759,1.673415,3.783698
40,7.009068,0.900545,0.608769,0.223787,1.733101,3.986768
41,5.648646,0.988844,0.201799,0.032864,1.223506,5.476103
42,6.985113,0.818000,0.449129,0.437402,1.704531,3.534134

In [16]:
# Import ResNet50 ternary classification results 
ternary_resnet50_df = pd.read_csv("experiments/resnet50_v1/experiments.csv")

In [21]:
# Total accuracies
ternary_resnet50_df["acc_total"] = ternary_resnet50_df["acc_normal"] + ternary_resnet50_df["acc_benign"] + ternary_resnet50_df["acc_malignant"]

# Residuals
residuals = 1 - ternary_resnet50_df[cols]
ternary_resnet50_df["weighted_residual"] = (residuals * weights).sum(axis=1)

# Display
ternary_resnet50_df[["training_time_min","acc_normal","acc_benign","acc_malignant", "acc_total", "weighted_residual"]]

,training_time_min,acc_normal,acc_benign,acc_malignant,acc_total,weighted_residual
0,3.837991,0.986192,0.000000,0.000000,0.986192,6.013808
1,6.810179,0.998649,0.000000,0.000000,0.998649,6.001351
2,4.800461,0.995498,0.000000,0.000000,0.995498,6.004502
3,3.872795,0.610986,0.517707,0.046948,1.175641,5.165807
4,4.231317,0.998949,0.000000,0.000000,0.998949,6.001051
5,3.868435,0.724599,0.436762,0.044601,1.205962,5.223473
6,8.093686,0.995047,0.000000,0.000000,0.995047,6.004953
7,8.157935,0.995047,0.000000,0.000000,0.995047,6.004953
8,8.082360,0.995197,0.000000,0.000000,0.995197,6.004803
9,9.387366,0.985742,0.000000,0.000000,0.985742,6.014258
10,9.326296,0.791235,0.001686,0.016432,0.809353,6.139664
11,9.413448,0.997749,0.000000,0.000000,0.997749,6.002251
12,2.082465,0.001051,0.112985,0.957746,1.071782,2.941994
13,2.050978,0.001051,0.112985,0.957746,1.071782,2.941994
14,2.052460,0.000750,0.483980,0.615023,1.099754,3.571196
15,2.039288,0.003602,0.224283,0.856808,1.084693,3.120601
16,9.415466,0.997299,0.000000,0.000000,0.997299,6.002701
17,9.462096,0.248837,0.411467,0.063380,0.723684,5.674708
18,9.326090,0.303617,0.330523,0.028169,0.662309,5.922661
19,9.381580,0.677623,0.037099,0.011737,0.726459,6.201230
20,2.052448,0.001201,0.271501,0.816901,1.089603,3.188192
21,3.341375,0.000000,0.005059,1.000000,1.005059,2.989882
22,3.896742,0.003902,0.023609,0.988263,1.015774,2.995829
23,3.912012,0.515083,0.013491,0.753521,1.282095,3.443851
24,3.936050,0.521237,0.013491,0.746479,1.281206,3.465866
25,3.930072,0.669218,0.008432,0.561033,1.238683,4.069787
26,3.893696,0.418880,0.244519,0.481221,1.144620,4.167198
27,3.944126,0.447396,0.236088,0.462441,1.145925,4.230663
28,3.871616,0.436740,0.236088,0.471831,1.144659,4.203760
29,6.461440,0.368453,0.406408,0.326291,1.101152,4.513567
30,5.964611,0.692931,0.028668,0.518779,1.240378,4.174616
31,6.019810,0.695182,0.028668,0.516432,1.240282,4.181754

In [22]:
# Total time in hours and average time in minutes taken
print((ternary_resnet50_df["training_time_min"].sum())/60)
print(ternary_resnet50_df["training_time_min"].mean())

2.9486114451620313
5.528646459678809

In [24]:
# Import ResNet50 binary classification results
binary_resnet50_df = pd.read_csv("experiments/binary_resnet50_roc_auc/roc_auc_binary_experiments.csv")

In [27]:
# Total time in hours and average time in minutes taken
print((binary_resnet50_df["training_time_min"].sum())/60)
print(binary_resnet50_df["training_time_min"].mean())

2.8103841520680324
6.245298115706738

In [30]:
# Total accuracies
binary_resnet50_df["acc_total"] = binary_resnet50_df["acc_normal"] + binary_resnet50_df["acc_abnormal"]

# Residuals
residuals = 1 - binary_resnet50_df[["acc_normal","acc_abnormal"]]
binary_weights = pd.Series({
    "acc_normal": 1,
    "acc_abnormal": 3
})
binary_resnet50_df["weighted_residual"] = (residuals * binary_weights).sum(axis=1)

# Display
binary_resnet50_df[["training_time_min","acc_normal","acc_abnormal","acc_total","weighted_residual"]]

    training_time_min  acc_normal  acc_abnormal  acc_total  weighted_residual
0            3.377795    0.159238      0.967615   1.126853           0.937916
1            4.317126    0.582771      0.693817   1.276588           1.335777
2            4.254502    0.205613      0.985280   1.190893           0.838548
3            4.249970    0.681675      0.552502   1.234177           1.660818
4            4.230497    0.613387      0.651619   1.265007           1.431755
5            4.260657    0.266096      0.960746   1.226842           0.851666
6            4.262034    0.648207      0.632974   1.281180           1.452873
7            4.285333    0.612937      0.645731   1.258668           1.449870
8            4.273666    0.642804      0.623160   1.265964           1.487717
9            4.283593    0.588924      0.671246   1.260170           1.397337
10           4.253412    0.589074      0.683023   1.272097           1.361858
11           4.255163    0.580519      0.676153   1.256672           1.391021
12           4.320783    0.188954      0.947988   1.136942           0.967081
13           7.844699    0.475462      0.820412   1.295874           1.063302
14           7.870057    0.568062      0.766438   1.334500           1.132625
15           5.322819    0.567312      0.753680   1.320992           1.171648
16           8.579294    0.627945      0.716389   1.344334           1.222889
17          11.967824    0.643554      0.712463   1.356017           1.219056
18          15.204274    0.526339      0.783121   1.309460           1.124298
19           5.258660    0.558307      0.723258   1.281565           1.271919
20           5.244368    0.565061      0.738960   1.304021           1.218060
21           6.127209    0.636500      0.693817   1.330318           1.282048
22           5.284378    0.572115      0.759568   1.331683           1.149181
23          12.802319    0.648357      0.593719   1.242076           1.570485
24           6.176307    0.610236      0.544652   1.154887           1.755810
25           5.270605    0.570464      0.720314   1.290778           1.268594
26          11.045703    0.581902      0.775635   1.357537           1.091194

In [31]:
# Import VGG16 binary classification results
binary_vgg_df = pd.read_csv("vgg_experiments_log.csv")

In [33]:
# Total time in hours and average time in minutes taken
print((binary_vgg_df["training_time_min"].sum())/60)
print(binary_vgg_df["training_time_min"].mean())

3.2496663700209725
7.221480822268827

In [32]:
# Accuracy totals
binary_vgg_df["acc_total"] = binary_vgg_df["acc_normal"] + binary_vgg_df["acc_abnormal"]

# Residuals
residuals = 1 - binary_vgg_df[["acc_normal","acc_abnormal"]]
binary_weights = pd.Series({
    "acc_normal": 1,
    "acc_abnormal": 3
})
binary_vgg_df["weighted_residual"] = (residuals * binary_weights).sum(axis=1)

# Display
binary_vgg_df[["training_time_min","acc_normal","acc_abnormal","acc_total","weighted_residual", "roc_auc"]]

,training_time_min,acc_normal,acc_abnormal,acc_total,weighted_residual,roc_auc
0,4.610989,0.896443,0.075564,0.972007,2.876864,0.445458
1,4.596760,0.897794,0.074583,0.972377,2.878457,0.445069
2,4.557118,0.903347,0.072620,0.975967,2.878793,0.445721
3,4.478940,0.954375,0.020608,0.974983,2.983800,0.459402
4,4.451888,0.954075,0.021590,0.975665,2.981156,0.459271
5,4.604842,0.954375,0.020608,0.974983,2.983800,0.459384
6,4.477366,0.954075,0.021590,0.975665,2.981156,0.459327
7,4.503540,0.954075,0.021590,0.975665,2.981156,0.459223
8,11.555963,0.184602,0.930324,1.114925,1.024427,0.639576
9,4.677298,0.252889,0.790972,1.043861,1.374196,0.532671
10,4.562982,0.244334,0.796860,1.041194,1.365087,0.530213
11,4.556046,0.250938,0.792934,1.043872,1.370259,0.533010
12,5.322276,0.627795,0.300294,0.928090,2.471321,0.440735
13,4.547001,0.264746,0.783121,1.047866,1.385892,0.534018
14,4.630984,0.276302,0.777233,1.053535,1.392000,0.536364
15,9.773206,0.530092,0.683023,1.213114,1.420841,0.610271
16,4.613135,0.363350,0.788027,1.151377,1.272568,0.590685
17,4.674228,0.396668,0.774289,1.170957,1.280466,0.601058
18,6.103374,0.274051,0.879293,1.153344,1.088069,0.580414
19,19.364077,0.182801,0.932287,1.115087,1.020340,0.558936
20,19.595808,0.195107,0.926398,1.121506,1.025697,0.561291
21,19.308122,0.184602,0.931305,1.115907,1.021483,0.560940
22,9.766312,0.501426,0.691855,1.193281,1.423010,0.601357
23,4.696909,0.263995,0.867517,1.131512,1.133453,0.590460
24,9.585697,0.526790,0.669284,1.196073,1.465359,0.604030
25,6.696245,0.344890,0.815505,1.160395,1.208594,0.580856
26,4.668874,0.308646,0.859898,1.168544,1.111659,0.615003

In [35]:
# Import MyCNN binary classification results
my_cnn_binary_df = pd.read_csv("MyBinaryCNN_experiments_log.csv")

In [36]:
# Display
my_cnn_binary_df[["training_time_min","acc_normal","acc_abnormal","roc_auc"]]

   training_time_min  acc_normal  acc_abnormal   roc_auc
0          16.147600    0.796638      0.865554  0.911689
1          16.196259    0.797073      0.852792  0.905991
2          16.568597    0.684038      0.951269  0.905730